/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empmgmt.gui;

import empmgmt.dbutil.DBConnection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class OptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptionsFrame
     */
    public OptionsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrAddEmp = new javax.swing.JRadioButton();
        jrSearchEmp = new javax.swing.JRadioButton();
        jrShowAllEmp = new javax.swing.JRadioButton();
        jrQuite = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        jrDelectEmp = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Your Choice");

        buttonGroup1.add(jrAddEmp);
        jrAddEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrAddEmp.setText("Add Employee");

        buttonGroup1.add(jrSearchEmp);
        jrSearchEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrSearchEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrSearchEmp.setText("Search Employee");

        buttonGroup1.add(jrShowAllEmp);
        jrShowAllEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrShowAllEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrShowAllEmp.setText("Show All Employee");

        buttonGroup1.add(jrQuite);
        jrQuite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrQuite.setForeground(new java.awt.Color(255, 255, 255));
        jrQuite.setText("Quite");
        jrQuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrQuiteActionPerformed(evt);
            }
        });

        btnDoTask.setBackground(new java.awt.Color(102, 102, 102));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 255, 255));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        jrDelectEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrDelectEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrDelectEmp.setText("Delect Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jrShowAllEmp)
                        .addComponent(jrDelectEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jrQuite, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jrAddEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(jrSearchEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrSearchEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrShowAllEmp)
                .addGap(18, 18, 18)
                .addComponent(jrDelectEmp)
                .addGap(18, 18, 18)
                .addComponent(jrQuite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnDoTask)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed

        if(validateInput() == false)
        {
            JOptionPane.showConfirmDialog(null,"Please Make a Selection First","No Selection!",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        JFrame userChoiceFrame = null;
        if(jrAddEmp.isSelected())
        {
           userChoiceFrame =new AddEmployeeFrame();
//        AddEmployeeFrame adEmp =new AddEmployeeFrame();
//        adEmp.setVisible(true);
//        this.dispose();
        }
        else if(jrSearchEmp.isSelected())
        {     
            userChoiceFrame = new SearchEmployeeFrame();
//            SearchEmployeeFrame searchEmp = new SearchEmployeeFrame();
//            searchEmp.setVisible(true);
//            this.dispose();
        }
        else if(jrShowAllEmp.isSelected())
        {
             userChoiceFrame = new ViewAllEmployeeFrame();
//            ViewAllEmployeeFrame showEmp = new ViewAllEmployeeFrame();
//            showEmp.setVisible(true);
//            this.dispose();
        }
        
        else if (jrDelectEmp.isSelected())
        {
            userChoiceFrame = new DeleteEmployeeFrame();
        }
        else
        {
            JOptionPane.showConfirmDialog(null,"Thanks for Using this apps","Thanks",JOptionPane.INFORMATION_MESSAGE);
            DBConnection.closeConnection();
            System.exit(0);
        }
        userChoiceFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void jrQuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrQuiteActionPerformed
       System.exit(0);

    }//GEN-LAST:event_jrQuiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrAddEmp;
    private javax.swing.JRadioButton jrDelectEmp;
    private javax.swing.JRadioButton jrQuite;
    private javax.swing.JRadioButton jrSearchEmp;
    private javax.swing.JRadioButton jrShowAllEmp;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
       if(jrAddEmp.isSelected()== false &&jrSearchEmp.isSelected()== false && jrShowAllEmp.isSelected()==false && jrQuite.isSelected()==false && jrDelectEmp.isSelected()==false)
        return false;
        return true;   
    }
}
